/* FETCH EVENTS */
export const FETCH_EVENTS_STARTED = 'counter/FETCH_EVENTS_STARTED';
export const FETCH_EVENTS_SUCCEEDED = 'counter/FETCH_EVENTS_SUCCEEDED';
export const FETCH_EVENTS_FAILED = 'counter/FETCH_EVENTS_FAILED';

/* FETCH EVENT */
export const FETCH_EVENT_STARTED = 'counter/FETCH_EVENT_STARTED';
export const FETCH_EVENT_SUCCEEDED = 'counter/FETCH_EVENT_SUCCEEDED';
export const FETCH_EVENT_FAILED = 'counter/FETCH_EVENT_FAILED';
